---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.1
    hooks:
      - id: trailing-whitespace
        files: .*\.(yaml|yml|py|sh|groovy)$
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
        additional_dependencies:
          - hacking<1.2.0,>=1.1.0
      - id: check-yaml
        files: .*\.(yaml|yml|py|sh|groovy)$
        exclude: .*/(layouts|topologies)/.*
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.13.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        exclude: .*/(layouts|topologies)/.*
  - repo: https://github.com/openstack-dev/bashate.git
    rev: 0.6.0
    hooks:
      - id: bashate
        entry: bashate --error . --verbose --ignore=E006,E002,E003
  - repo: https://github.com/willthames/ansible-lint.git
    rev: v4.2.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        files: \.py
  - repo: local
    hooks:
      - id: Jenkinsfile-linter
        name: Linting Jenkinsfile
        files: Jenkinsfile
        entry: ./jenkinslint.sh
        language: script
